// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music_Band_Database_API.Data;

namespace Music_Band_Database_API.Migrations
{
    [DbContext(typeof(Music_Band_Database_APIContext))]
    [Migration("20200410100101_Band")]
    partial class Band
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Music_Band_Database_API.Models.BandDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Album_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Album_ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Band_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BandDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
